### ISSUE TITLE
Implement Create logic for Interesting Facts block

### ISSUE THREAD

**Issue by MrVenik** [project-studying-dotnet/Streetcode-Admin#72]
## Tasks
- [x] Create DTO for creating new fact.
- [x] Create needed endpoints in related controller.
- [x] Create mediator command for creating new fact.
- [x] Create mediator handler for creating new fact.
- [x] Write tests for mediator handler.

### Additional content
- prefered branch name: `feat/interesting_facts/create_logic` or `feat/interesting_facts/add_create_logic` or something else that would describe that you are working on this task.

**Comment by MishaPolishchuk** [comment]
Great
In addition, it`s worth also adding `Create mediator **query** to **read/get** a fact if needed
