### ISSUE TITLE
Implement Delete logic for Interesting Facts block

### ISSUE THREAD

**Issue by MrVenik** [project-studying-dotnet/Streetcode-Admin#77]
## Tasks
- [x] Create DTO for delete existent fact.
- [x] Create needed endpoints in related controller.
- [x] Create mediator command for deleting existent fact.
- [x] Create mediator handler for deleting existent fact.
- [x] Write tests for mediator handler.

### Additional content
- prefered branch name: `feat/interesting_facts/delete_logic` or `feat/interesting_facts/add_delete_logic` or something else that would describe that you are working on this task.
